################################################################################################################
## https://docs.github.com/pt/actions/automating-builds-and-tests/building-and-testing-nodejs
################################################################################################################

name: ci-golang-workflow

on: [push] # Everytime I run "git push"
# on:
#   pull_request:
#     branches:
#       - develop

jobs:
  check-application:
    runs-on: ubuntu-latest # Will run in Ubunto

    strategy:
      matrix:
        go: ["1.14", "1.15"]

    steps:
      # Running github action -> github.com/actions/*
      - uses: actions/checkout@v2 # to take all pushed data and download to this Ubuntu machine
      - uses: actions/setup-go@v2 # to prepare Go env
        with:
          go-version: ${{ matrix.go }} # strategy / matrix / go
      # Running commands
      - run: go test
      - run: go run math.go
