################################################################################################################
## https://docs.github.com/pt/actions/automating-builds-and-tests/building-and-testing-nodejs
################################################################################################################

name: ci-golang-workflow

# on: [push] # Everytime I run "git push"
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest # Will run in Ubunto

    strategy:
      matrix:
        go: ["1.14", "1.15"]

    steps:
      # Running github action -> github.com/actions/*
      - uses: actions/checkout@v2 # to take all pushed data and download to this Ubuntu machine
      - uses: actions/setup-go@v2 # to prepare Go env
        with:
          go-version: ${{ matrix.go }} # strategy / matrix / go
      # Running commands
      - run: go test
      - run: go run math.go

      # Docker Setup
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # The result of this action we´ll use in another step
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: robertomoreloowlish/ci_cd_go:latest
